language: php

notifications:
  email:
    recipients:
      - kennethhendricks@catalyst-au.net

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6


env:
  global:
    - IGNORE_PATHS=javascript
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE

matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
    # Test with PHP 7.1
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
#  - moodle-plugin-ci phpcpd        #temp disable
#  - moodle-plugin-ci phpmd         # phpmd is a bit overzealous
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
